config/routes.rb
HitSns::Application.routes.draw do
  match '/home',  to: 'static_pages#home', via: 'get'
  match '/help',  to: 'static_pages#help', via: 'get'
	get 'courses/search'
	post 'courses/search_result' => 'courses#search_result'
	post 'courses/register' => 'courses#register'
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :courses
	match '/signup',  to: 'users#new',        via: 'get'
	match '/signin',  to: 'sessions#new',		  via: 'get'
	match '/signout', to: 'sessions#destroy', via: 'delete'
	root 'static_pages#home'
	match '/search_course', to: 'users#search_course', via: 'get'

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :user_courses
	has_many :users , :through => :user_courses
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_courses
	has_many :courses ,:through => :user_courses
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email ,presence: true, format: { with: VALID_EMAIL_REGEX}
	validates :name  ,presence: true, length: { maximum:50,minimum:4},
								    uniqueness: true
	has_secure_password
	validates :password, length: {minimum: 6 }
	
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end

end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :signed_in_user
	def index
		@courses = Course.all
	end
	def search
	end
	def search_result
		@keyword = params[:keyword]
		if !@keyword.blank?
      @courses = Course.where(["name LIKE ?", "%#{@keyword}%"])
    else
      @courses = Course.order("created_at DESC")
    end
	end
	def register
		@checked_courses=[]
		@checked = params[:courses_id]
		@checked.each do |c|
			course = Course.where("id = '#{c}")
			#現在のユーザーに新しいcourseの関連づけ
			current_user.user_courses.create(course_id:c)
			@checked_courses.push course 
		end
	end
end

app/controllers/sessions_controller.rb
#coding:utf-8
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user 

			#make user sign in ,and connect user page
		else
			#show error message,and redirect itself
			flash.now[:error] = 'メールアドレスかパスワードに誤りがあります'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action:signed_in_user, only:[:index,:edit,:update,:destroy]
	before_action :correct_user, only:[:edit, :update]
	before_action :admin_user, only: :destroy

	def show
		@user = User.find(params[:id])
		@courses = @user.courses
	end

  def new
		@user = User.new
  end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to the Hit-SNS!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end
	
	def search_course
	end

	def index
		@users = User.all
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end 

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed"
		redirect_to users_url
	end
	private
		
		def user_params #provides Strong parameter
			params.require(:user).permit(:name,:email,:password,:password_confirmation)
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_path) unless current_user?(@user)
		end 
		def admin_user
			redirect_to(root_path) unless current_user.admin?
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end
	def current_user=(user)
	  @current_user = user
	end
	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user 
		store_location
		redirect_to signin_url, notice:"Please sign in." unless signed_in?
	end
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end

	def signed_in?
		!current_user.nil?
	end
	def sign_out
		self.current_user=nil
		cookies.delete(:remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user,options = {size:50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url,alt:user.name, class:"gravatar")
	end
end

app/views/courses/_course.html.erb
<ul>
	<%= course.day %> | <span class="content"><%= course.name %> </span>
</ul>

app/views/courses/index.html.erb
<% provide(:title, 'All courses') %>
<h1> All courses </h1>

<ul class = "courses">
			<%= render @courses %>
</ul>

app/views/courses/register.html.erb
<% @checked_courses.each do |c| %>
	<%= c %>
<% end %>

app/views/courses/search.html.erb
<% provide(:title, 'Search Course') %>
<h1> Search courses </h1>
<%= form_tag(:controller=>"courses",:action=>"search_result") do %>
	<%= text_field_tag 'keyword' %>
	<%= submit_tag "検索" %>
<% end %>

app/views/courses/search_result.html.erb
<ul class = "courses">
  <%= form_tag :controller=>"courses",:action=>"register"  %>
		<% @courses.each do |course| %>
			<%= check_box_tag 'courses_id[]', course.id, false, {} %>
			<%= label_tag :course_id, course.name+' | '+course.teacher + ' | ' +course.day, :value => course.id %>
		<br>
		<% end %>
		<%= submit_tag "授業登録" %> 
</ul>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HitSNS", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      <li><%= link_to "ヘルプ", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "ユーザー", users_path %></li>
        <li><%= link_to "講義情報", courses_path %></li>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            アカウント <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", current_user %></li>
            <li><%= link_to "設定", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "ログアウト", signout_path, method: "delete" %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "ログイン", signin_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HitSNS | <%= yield(:title) %></title>
  <link data-turbolinks-track href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/cerulean/bootstrap.min.css" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
	<div class = "container">
		<% flash.each do |key,value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= debug(params) if Rails.env.development? %>
		<footer><hr><p>&copy; Hitotsubashi CO-WORK</p></footer>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id = "error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li> * <%= msg %> </li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/help.html.erb
<h1>ヘルプ</h1>
<dl>
  <dt>今後登録対象の大学は拡大しますか？</dt>
  <dd>部長次第。</dd>
</dl>
<dl>
  <dt>利用・登録は無料ですか？</dt>
  <dd>逆にこれで金取れると思う？</dd>
</dl>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to Gakusy!</h1>
  <p style="font-size:18px">
  	Gakusyは、大学生(の+による+のための)SNSです。
  	<br>講義やサークルなど学生生活をサバイブ＆エンジョイするための情報や、新しい友人との出会いが得られます！
  	<br>現在は一橋大学の学生が登録可能です。
  </p>
  <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
</div>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size:52 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		<%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1> Update your profile </h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>
<!--
			<%= f.label :grade %>
			<%= f.text_field :grade %>

			<%= f.label :department %>
			<%= f.text_field :department %>
--!>
			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>

		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">change</a>
 	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1> All users </h1>

<ul class = "users">
			<%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<br/>
			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1>
	<%= gravatar_for @user %>
	<%= @user.name%>
</h1>
	<%= @user.grade%><% if @user.grade.nil? == false %> 年<% end %>
	<%= @user.department%>
	<%= @user.comment%>
	<div class="span8">
		hogea
		<% if @user.courses.any? %>
			<h3>Courses(<%= @user.courses.count %>)</h3>
			<ol>
				<%= render @courses %>
			</ol>
		<% end %>
		<% if current_user?(@user) %>
			<%= link_to "授業の登録",courses_search_path %></li>
		<% end %>
	</div>